version: '3.1'

services:
  pardjs-auth-service:
    container_name: pardjs-auth-service
    image: registry.cn-shanghai.aliyuncs.com/pardjs/auth-service:1.2.2
    restart: always
    environment: 
      DB_URL: postgres://pardjs:example@db:5432/pardjs-auth-service
    links: 
      - pardjs-auth-service-db:db
    ports:
      - 5000:5000
    networks: 
      - pardjs-auth-service
networks: 
  pardjs-auth-service: